FROM ubuntu:20.04

# 패키지 설치 중 상호작용 방지
ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update
RUN apt-get install -y python3 python3-pip python3-dev build-essential

RUN apt-get install git -y

RUN mkdir /app
WORKDIR /app

RUN git init
RUN git config core.sparseCheckout true
RUN echo "train_server/" >> .git/info/sparse-checkout
RUN git remote add -f origin https://github.com/dnfwlxo11/everyCanAI.git
RUN git pull origin master

COPY ./app /app/train_server
COPY ./entrypoint.sh /app

EXPOSE 5000

RUN pip3 install -r train_server/requirements.txt

RUN chmod +x ./entrypoint.sh

ENTRYPOINT ["./entrypoint.sh"]
