FROM ubuntu:20.04

# 패키지 설치 중 상호작용 방지
ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update
RUN apt-get install wget -y
RUN apt-get install xz-utils -y
RUN apt-get install python3.8 -y
RUN apt-get install python3-pip -y
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3.8 1
RUN update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 1
RUN apt -y install build-essential
RUN apt-get install zlib1g-dev

RUN apt-get install git -y

RUN mkdir /app
WORKDIR /app

RUN git init
RUN git config core.sparseCheckout true
RUN echo "train_server/" >> .git/info/sparse-checkout
RUN git remote add -f origin https://github.com/dnfwlxo11/everyCanAI.git
RUN git pull origin master

COPY ./app /app/train_server
COPY ./entrypoint.sh /app
COPY ./model_download.py /app/train_server

EXPOSE 5000

RUN python -m pip install -r train_server/requirements.txt

RUN chmod +x ./entrypoint.sh

ENTRYPOINT ["./entrypoint.sh"]
