FROM node:12

ENV GIT_USER=dnfwlxo11
ENV GIT_ACCESS_KEY=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

# 패키지 설치 중 상호작용 방지
ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get install git -y

RUN mkdir /app
WORKDIR /app

RUN git init
RUN git config core.sparseCheckout true
RUN echo "app_server/" >> .git/info/sparse-checkout

# RUN git clone -b daein https://${GIT_USER}:${GIT_ACCESS_KEY}@github.com/dnfwlxo11/flask_classification_sampleServer.git ./app_server

RUN git remote add -f origin https://${GIT_USER}:${GIT_ACCESS_KEY}@github.com/dnfwlxo11/flask_classification_sampleServer.git
RUN git pull origin daein

COPY ./app /app
RUN mkdir /app/app_server/uploads
RUN mkdir /app/app_server/inference

EXPOSE 3000

RUN chmod +x ./entrypoint.sh
RUN npm install pm2 -g

ENTRYPOINT ["./entrypoint.sh"]
