version: '3'
services:
  app:
    image: flask
    restart: always
    container_name: daein_classification
    build:
      context: flask
      dockerfile: Dockerfile
    ports:
      - "16005:5000"
    environment:
      - BRANCH_NAME=master
    volumes:
      - ./flask/app/models:/app/server/models
      - ./flask/app/output:/app/server/output
      - ./flask/app/db:/app/server/db
  redis:
    image: redis
    restart: always
    container_name: daein_redis
    build:
      context: redis
      dockerfile: Dockerfile
    ports:
      - "16006:6379"
    volumes:
      - ./redis/app:/data