version: '3'
services:
  every-app-server:
    image: nodejs
    restart: always
    container_name: daein_web
    build:
      context: nodejs
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - BRANCH_NAME=daein
    volumes:
      - ./nodejs/app/:/app/app_server/uploads
  every-train-server:
    image: flask
    restart: always
    container_name: daein_classification
    build:
      context: flask
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - BRANCH_NAME=daein
    volumes:
      - ./flask/app/models:/app/train_server/models
      - ./flask/app/output:/app/train_server/output
      - ./flask/app/db:/app/train_server/db
  every-redis-db:
    image: redis
    restart: always
    container_name: daein_redis
    build:
      context: redis
      dockerfile: Dockerfile
    ports:
      - "6379:6379"
    volumes:
      - ./redis/app:/data